# Generated by Django 6.0.7 on 2026-07-09 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название уровня')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уровень языка',
                'verbose_name_plural': 'Уровни языка',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Номер урока по счету')),
                ('title', models.CharField(max_length=200, verbose_name='Тема урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание/План урока')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.languagelevel', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название материала')),
                ('material_type', models.CharField(choices=[('pdf', 'Учебник / PDF'), ('video', 'Видео'), ('game', 'Интерактивная игра'), ('link', 'Внешняя ссылка')], max_length=20, verbose_name='Тип контента')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/files/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка (Видео/Игра)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала занятий')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='courses.languagelevel', verbose_name='Уровень')),
                ('students', models.ManyToManyField(blank=True, related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
